sudo: false
language: ruby
rvm:
  - 2.5.0
before_install: gem install bundler -v 1.16.1
before_script: RAILS_ENV=test bundle exec rake db:drop db:create db:migrate || echo 'Ignore schema.rb error https://source.xing.com/growth/inquiry/pull/92'
